# Generated by Django 4.2.11 on 2024-03-18 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('udemy_cbvs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='name',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='principal',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
